# -*- coding: utf-8 -*-
{
    'name': 'Crossnexion - Facturación Electrónica',
    'summary': 'Modulo de facturación electrónica de localización paraguaya',
    'author': 'Crossnexion EAS',
    'website': 'www.crossnexion.com',
    'category': 'Accounting',
    'license': 'OPL-1',
    'version': '25.7.4',
    'depends': [
        'base',
        'account',
        'contacts',
        'uom',
        'sale',
        'stock',
        'sale_stock',
        'l10n_latam_base',
        'l10n_py',
        'fleet',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/account_authorization_rules.xml',
        'data/res.country.csv',
        'data/res.partner.ope.type.csv',
        'data/res.company.transactiontype.csv',
        'data/res.company.taxtype.csv',
        'data/res.presence.csv',
        'data/res.delivery.note.csv',
        'data/res.delivery.responsible.csv',
        'data/res.negotiation.condition.csv',
        'data/res.credit.debit.note.csv',
        'data/res.document.format.csv',
        'data/res.document.format.type.csv',
        'data/cron_de_status.xml',
        'data/res.partner.search.config.xml',
        'data/report_paperformat.xml',
        'reports/invoice.xml',
        'views/res_config_settings.xml',
        'views/res_partner.xml',
        'views/res_country.xml',
        'views/account_authorization.xml',
        'views/account_move.xml',
        'views/res_company.xml',
        'views/res_partner_ope_type.xml',
        'views/res_presence.xml',
        'views/product_template.xml',
        'views/res_users.xml',
        'views/stock_picking.xml',
        'views/res_delivery.xml',
        'views/fleet_vehicle.xml',
        'views/res_creditdebit_note.xml',
        'views/res_document_format.xml',
        'wizard/res_cancel_document_wizard.xml',
        'wizard/de_downtime_event_wizard.xml',
        'wizard/res_partner_search_config.xml',
    ],
}
